import { FormItem } from '../interfaces/form-item.interface';

export const draggableFormItem: FormItem[] = [
  {
    content: 'short-text',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'long-text',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'number',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'date',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'time',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'date-time',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'checkbox',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'radio',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'email',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'select',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
  {
    content: 'upload',
    effectAllowed: 'move',
    disable: false,
    handle: false,
    fieldName: '',
    helpText: '',
    options: [],
    comment: '',
    validation: {
      required: false,
      minLength: '',
      maxLength: '',
      min: '',
      max: '',
      pattern: '',
      fileTypes: '',
    },
  },
];
